---
title: "preliminary analysis of Fr with EnKF"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)

#### set working directory
pathDAPPER = '/Users/laurapuckett/Documents/Research/Current/DAPPER/' 
EnKF_directory = '/Users/laurapuckett/Documents/Research/Current/DAPPER/analysis_tools/'
setwd(EnKF_directory)

#### source required functions
source('prepare_update_states.R')
source('update_states.R')
source('EnKF_DAPPER.R')

#### define variables needed for DAPPER functions
working_directory = pathDAPPER # this is referenced in prepare_update_states(), and prepare_obs()
input_directory = '/Users/laurapuckett/Documents/Research/Current/DAPPER_inputdata/'
output_directory = '/Users/laurapuckett/Documents/Research/Current/DAPPER_projects/'
plotlist = c(40001) #THIS IS Duke Forest
focal_plotID = plotlist #
  
  
#---------------------------------------------------------

nmembers = 200
NO_UNCERT = FALSE
ADD_NOISE_TO_OBS = FALSE
USE_SYNTHETIC_DATA = TRUE
USE_OBS_COORD = FALSE
USE_OBS_CONTRAINT = TRUE
  
# Define variables needed for prepare_update_states or update_states
plotnum = 1
all_studies = c('/Duke/TIER4_Duke')
  
original_data = read.csv(file = paste(EnKF_directory,"/duke_input.csv", sep = ""), header = TRUE, sep = ",")
realdata = original_data[which(original_data$PlotID == 40001), ]
observed = realdata[which(realdata$LAI != "NA" & realdata$LAI != -99 & realdata$Age != -99), ]
#years = observed$Year
#startyear = min(years)
#startmonth = min(observed$Month[which(observed$Year == startyear)])
#endyear = max(years)
#endmonth = max(realdata$month[which(realdata$year == endyear)])
#start_age = observed$Age[which(observed$Year == startyear && observed$Month == startmonth)]
#nmonths = (endyear - startyear +1)*12
#observed_months = (observed$Year-startyear)*12 + observed$Month


lower_psi = 0.0001
higher_psi = 0.001
```


```{r, echo = FALSE}
### (1) all LAI, Fr = site default, lower psi
setwd(EnKF_directory)
observed = realdata[which(realdata$LAI != "NA" & realdata$LAI != -99 & realdata$Age != -99), ]
EnKF_DAPPER(psi = lower_psi, init_Fr = 0.8780736, observed = observed)

```
```{r, echo = FALSE}
### (2) all LAI, Fr = 0.2, lower psi
observed = realdata[which(realdata$LAI != "NA" & realdata$LAI != -99 & realdata$Age != -99), ]
setwd(EnKF_directory)
EnKF_DAPPER(psi = lower_psi, init_Fr = 0.2, observed = observed)

```
```{r, echo = FALSE}
### (3) only winter LAI, Fr = default, lower psi
observed = realdata[which(realdata$LAI != "NA" & realdata$LAI != -99 & realdata$Age != -99), ]
observed = observed[which(observed$Month == 12 | observed$Month == 1 | observed$Month == 2), ]
EnKF_DAPPER(psi = lower_psi, init_Fr = 0.8780736, observed = observed)

```
```{r, echo = FALSE}
 ### (4) only winter LAI, Fr = 0.2, lower psi
observed = realdata[which(realdata$LAI != "NA" & realdata$LAI != -99 & realdata$Age != -99), ]
observed = observed[which(observed$Month == 12 | observed$Month == 1 | observed$Month == 2), ]
EnKF_DAPPER(psi = lower_psi, init_Fr = 0.2, observed = observed)

```

```{r, echo = FALSE}
### (5) all LAI, Fr = site default, higher psi
observed = realdata[which(realdata$LAI != "NA" & realdata$LAI != -99 & realdata$Age != -99), ]
EnKF_DAPPER(psi = higher_psi, init_Fr = 0.8780736, observed = observed)

```

```{r, echo = FALSE}
### (6) all LAI, Fr = 0.2, higher psi
observed = realdata[which(realdata$LAI != "NA" & realdata$LAI != -99 & realdata$Age != -99), ]
EnKF_DAPPER(psi = higher_psi, init_Fr = 0.2, observed = observed)

```
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
